app/run:
	dotnet watch run --project src/Buk.Account

app/test/unit:
	dotnet watch tests ---project tests/Buk.Account.Tests.Unit/

env/gen:
	anv generate --output ./src/Buk.Account --double-quote-separator
